server:
  port: 8088
  error:
    path: /error
spring:
  data:
    neo4j:
      # 数据库uri地址
      uri: bolt://39.102.46.180:7687  # bolt://localhost:7687
      # Neo4j配置
      username: neo4j
      password: 123456
  datasource:
    url: jdbc:mysql://39.102.46.180:3306/CUQADatabase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: cuqa
    password: cuqa_q8s63g
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.cusc.cuscai.mapper: DEBUG


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


remote-ai:
  qaai:
    url: http://10.108.211.93:7662

